class ForceCodeDictLoader:
    def load(self):
        return {
            0: "Random",
            1: "HP",
            2: "MP",
            3: "Attack",
            4: "Magic Attack",
            5: "Defense",
            6: "Attack Rate",
            7: "Defense Rate",
            8: "Critical DMG.",
            9: "Critical Rate",
            10: "Min Damage",
            11: "Min Damage",
            12: "Max HP Steal per hit",
            13: "Max MP Steal per hit",
            14: "UNKNOWN",
            15: "UNKNOWN",
            16: "UNKNOWN",
            17: "UNKNOWN",
            18: "UNKNOWN",
            19: "UNKNOWN",
            20: "UNKNOWN",
            21: "UNKNOWN",
            22: "UNKNOWN",
            23: "Attack",
            24: "Magic Attack",
            25: "Max Critical Rate",
            26: "Attack Rate",
            27: "UNKNOWN",
            28: "Critical DMG.",
            29: "Critical Rate",
            30: "Sword Skill Amp.",
            31: "Sword Skill Amp.",
            32: "Magic Skill Amp.",
            33: "Magic Skill Amp.",
            34: "HP Absorb Up",
            35: "MP Steal",
            36: "Evasion",
            37: "HP Auto Heal",
            38: "MP Auto Heal",
            39: "Add. Damage",
            40: "Add. Damage",
            41: "Skill EXP per skill",
            42: "Skill EXP per skill",
            43: "Alz Drop Amount",
            44: "Alz Drop Amount",
            45: "STR",
            46: "INT",
            47: "DEX",
            48: "STR, INT, DEX",
            49: "1slot item drop",
            50: "1slot item drop",
            51: "2slot item drop",
            52: "2slot item drop",
            53: "UNKNOWN",
            54: "UNKNOWN",
            55: "UNKNOWN",
            56: "Final Damage Increased",
            57: "Final Damage decreased",
            58: "All Attack UP",
            59: "Defense",
            60: "HP",
            61: "Level Down",
            62: "UNKNOWN",
            63: "Heal",
            64: "UNKNOWN",
            65: "UNKNOWN",
            66: "UNKNOWN",
            67: "Absorb Damage",
            68: "Reflect Damage",
            69: "Craft Mastery UP",
            70: "increase Battle Mode duration time",
            71: "Ignore Evasion",
            72: "Ignore Accuracy",
            73: "Ignore Damage Reduction",
            74: "Ignore Penetration",
            75: "Cancel Ignore Evasion",
            76: "AXP Bonus",
            77: "Skill EXP Bonus",
            78: "DMG Reduction",
            79: "Accuracy",
            80: "Penetration",
            81: "Cancel Ignore DMG Reduction",
            82: "UNKNOWN",
            83: "Resist Suppression",
            84: "UNKNOWN",
            85: "Resist Silence",
            86: "UNKNOWN",
            87: "UNKNOWN",
            88: "Increase Sp Regen",
            89: "UNKNOWN",
            90: "UNKNOWN",
            91: "UNKNOWN",
            92: "UNKNOWN",
            93: "UNKNOWN",
            94: "UNKNOWN",
            95: "UNKNOWN",
            96: "UNKNOWN",
            97: "Resist Critical Rate",
            98: "Resist Critical Damage",
            99: "Resist unable to move",
            100: "UNKNOWN",
            101: "Resist Down",
            102: "Resist Knock Back",
            103: "Resist Stun",
            104: "UNKNOWN",
            105: "Increase the Honor Point bonus",
            106: "Increase the EXP Bonus for Party",
            107: "EXP Bonus",
            108: "Pet EXP Bonus",
            109: "Alz Drop Rate Increase",
            110: "Increase Alz Bomb Rate",
            111: "??????",
            112: "Resist Skill Amp",
            113: "All Attack UP",
            114: "All Skill Amp. UP",
            115: "All Attack UP",
            116: "All Skill Amp. UP",
            117: "Increase Movement Speed",
            118: "Suppression chance",
            119: "Suppression duration",
            120: "Silence Chance",
            121: "Silence duration",
            122: "Root chance",
            123: "Root duration",
            124: "Boost HP Restoration",
            125: "Ignore Resist Critical Rate",
            126: "Resist Absolute Damage",
            127: "Ignore Resist Critical Damage",
            128: "Ignore Resist Skill Amp",
            129: "Ignore Resist Down",
            130: "Ignore Resist Knock Back",
            131: "Ignore Resist Stun",
            132: "Normal Attack DMG UP",
            133: "UNKNOWN",
            134: "UNKNOWN",
            135: "UNKNOWN",
            136: "UNKNOWN",
            137: "UNKNOWN",
            138: "Aura Mode Duration Increase",
            139: "Cancel Ignore Penetration",
            140: "WEXP UP",
            141: "Force Wing EXP UP",
            142: "Increased Box Drop Point",
            143: "Resist Auto DMG",
            144: "Increase Max BP",
            145: "Decrease BP Consumption",
            146: "UNKNOWN",
            147: "UNKNOWN",
            148: "PVP Resist Magic Skill Amp. UP",
            149: "PVP Resist Sword Skill Amp. UP",
            150: "PVP Resist All Skill Amp. UP",
            151: "PVE Magic Skill Amp UP",
            152: "PVE Sword Skill Amp UP",
            153: "PVE All Skill Amp. UP",
            154: "Number Of Targets for Valid Skill",
            155: "PVE Defense",
            156: "PVE DMG Reduction",
            157: "PVE Ignore Penetration",
            158: "PVE Critical DMG",
            159: "Increase Restoration Amount",
            160: "Deduct Protection",
            161: "Fluidization",
            162: "DMG Reduction",
            163: "PVE Penetration",
            164: "Fury Effect Obtained",
            165: "Reduce Restoration Amount",
            166: "Prevent HP Restoration",
            167: "Movement Speed",
            168: "Petrified",
            169: "Target Fix",
            170: "Resist Irrecoverable Condition",
            171: "HP",
            172: "PVP All Skill Amp",
            173: "PVP Critical DMG",
            174: "PVP Magic Skill Amp",
            175: "PVP Sword Skill Amp",
            176: "PVP Attack",
            177: "PVE Attack",
            178: "PVP Magic Attack",
            179: "PVE Magic Attack",
            180: "PVP All Attack",
            181: "PVE All Attack",
            182: "PVP Attack",
            183: "PVE Attack Rate",
            184: "PVP Critical rate",
            185: "PVE Critical rate",
            186: "PVP Accuracy",
            187: "PVE Accuracy",
            188: "PVP Penetration",
            189: "PVP Defense",
            190: "PVP Defense Rate",
            191: "PVE Defense Rate",
            192: "PVP Evasion",
            193: "PVE Evasion",
            194: "PVP DMG Reduction",
            195: "PVP Ignore Penetration",
            196: "PVP Final DMG Reduction",
            197: "PVE Final DMG Reduction",
            198: "PVP Normal Attack DMG UP",
            199: "PVE Normal Attack DMG UP",
            200: "PVP Final DMG UP",
            201: "PVE Final DMG UP",
            202: "PVP Add DMG",
            203: "PVE Add DMG",
            204: "PVP Cancel Ignore DMG Reduction",
            205: "PVE Cancel Ignore DMG Reduction",
            206: "PVP Ignore Resist Critical DMG",
            207: "PVE Ignore Resist Critical DMG",
            208: "PVP Cancel Ignore Penetration",
            209: "PVE Cancel Ignore Penetration",
            210: "PVP Ignore Accuracy",
            211: "PVE Ignore Accuracy",
            212: "PVP Ignore Evasion",
            213: "PVE Ignore Evasion",
            214: "PVP Ignore Resist Skill Amp",
            215: "PVE Ignore Resist Skill Amp",
            216: "PVP Ignore Damage Reduction",
            217: "PVE Ignore Damage Reduction",
            218: "PVP Ignore Resist Critical Rate",
            219: "PVE Ignore Resist Critical Rate",
            220: "Arrival Skill Cooldown time decreased.",
            221: "Arrival Skill Buff Time UP",
            222: "UNKNOWN"
        }
